// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcqQLyUbHr9tSUB243iFCAzaC8W_vouRI',
    appId: '1:608256369708:web:ccadc0cb51d810e87a5d89',
    messagingSenderId: '608256369708',
    projectId: 'news-nabil',
    authDomain: 'news-nabil.firebaseapp.com',
    storageBucket: 'news-nabil.appspot.com',
    measurementId: 'G-3Z59121C82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf2SK5T9KzrGL_gtFmTf_C5UHnone333M',
    appId: '1:608256369708:android:ee93ea9e6f1121767a5d89',
    messagingSenderId: '608256369708',
    projectId: 'news-nabil',
    storageBucket: 'news-nabil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyjq6ggLKffBSsICI6QF5vaLGHE7hvLpY',
    appId: '1:608256369708:ios:1af18db701de249f7a5d89',
    messagingSenderId: '608256369708',
    projectId: 'news-nabil',
    storageBucket: 'news-nabil.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyjq6ggLKffBSsICI6QF5vaLGHE7hvLpY',
    appId: '1:608256369708:ios:1af18db701de249f7a5d89',
    messagingSenderId: '608256369708',
    projectId: 'news-nabil',
    storageBucket: 'news-nabil.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcqQLyUbHr9tSUB243iFCAzaC8W_vouRI',
    appId: '1:608256369708:web:bfa2187a382aa3ab7a5d89',
    messagingSenderId: '608256369708',
    projectId: 'news-nabil',
    authDomain: 'news-nabil.firebaseapp.com',
    storageBucket: 'news-nabil.appspot.com',
    measurementId: 'G-PKH4SC5E5E',
  );
}
